
test: test.cpp ../Virtualbox.cpp ../Virtualbox.h ../Hypervisor.cpp ../Hypervisor.h ../contextiso.cpp ../contextiso.h
	g++ -DOSX -lcurl -I.. -o test ../Virtualbox.cpp ../Hypervisor.cpp ../contextiso.cpp test.cpp
