
test: test.cpp ../Virtualbox.cpp ../Virtualbox.h ../Hypervisor.cpp ../Hypervisor.h ../contextiso.cpp ../contextiso.h
	g++ -DOSX -I.. -o test ../Virtualbox.cpp ../Hypervisor.cpp ../contextiso.cpp test.cpp -lcurl -lssl -lcrypto
